

package org.jetbrains.kotlin.formver.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.formver.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("formver.compiler-plugin/bugReproductions/booleanExistentialWitness")
@TestDataPath("$PROJECT_ROOT")
public class BugReproductionTestGenerated extends AbstractBugReproductionTest {
  @Test
  public void testAllFilesPresentInBooleanExistentialWitness() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/bugReproductions/booleanExistentialWitness"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("boolean_existential_witness.kt")
  public void testBoolean_existential_witness() {
    runTest("formver.compiler-plugin/bugReproductions/booleanExistentialWitness/boolean_existential_witness.kt");
  }
}
