# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Formal Verification Plugin CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup Z3
        id: z3
        uses: cda-tum/setup-z3@v1
        with:
          version: 4.8.7

      - name: Setup Z3_EXE
        run: echo "Z3_EXE=${{ steps.z3.outputs.z3-root }}/bin/z3" >> $GITHUB_ENV

      - name: Check z3 version
        run: $Z3_EXE --version

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Run detekt
        run: ./gradlew detekt
      - name: Check public API compatibility
        run: ./gradlew apiCheck
      - name: Run locality tests
        run: ./gradlew :formver.compiler-plugin:locality:test
      - name: Run all tests (conversion + verification)
        run: ./gradlew :formver.compiler-plugin:test
      - name: Report failing test results
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
